version: '3.8'
services:
  site:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
